### ISSUE TITLE
Real-time spectrogram analysis

### ISSUE THREAD

**Issue by EliaTolin** [SKKbySSK/coast_audio#13]
Is it possible to analyze the spectrogram with this library to analyze the frequencies coming from the microphone?

**Comment by SKKbySSK** [comment]
@ekuleshov 
Sorry for my late response.

> I could not figure out how to process audio data without having EncoderNode or something like MabPlaybackDeviceNode at the end of the audio graph.

Most of nodes have one `outputBus` and it has [read](https://github.com/SKKbySSK/coast_audio/blob/a9f5b1c78a6f60c1140ab267d06574dac741b897/packages/coast_audio/lib/src/node/bus/audio_output_bus.dart#L30-L32) function to process audio data.
So, you should be able to do that something like this.

```dart
final graphNode = GraphNode();
final sineNode = FunctionNode(function: const SineFunction(), format: format, frequency: freq);
final sineVolumeNode = VolumeNode(volume: 0.2);

graphNode.connect(sineNode.outputBus, sineVolumeNode.inputBus);
graphNode.connectEndpoint(sineVolumeNode.outputBus);

// Allocate 10 seconds audio buffer.
final frames = AllocatedAudioFrames(
  length: format.sampleRate * 10,
  format: format,
);

frames.acquireBuffer((buffer) {
  // Read the graph's output data
  final framesRead = graphNode.outputBus.read(buffer);
  final readBuffer = buffer.limit(framesRead);

  // do something on readBuffer
});
```

**Comment by SKKbySSK** [comment]
> Also it is somewhat cumbersome to get the audio position from within processor nodes, such as FftNode. You have to go all the way to decoder to get the position, as MabAudioPlayer.position method does. It would be really handy if ProcessorNodeMixin.process() method also had the AudioTime parameter along with the AudioBuffer.

Since `position` has different implications depending on the context and the processor node has responsible for processing audio data, not for calculating position, I don't think it is a good solution.

**Comment by ekuleshov** [comment]
> > Also it is somewhat cumbersome to get the audio position from within processor nodes, such as FftNode. You have to go all the way to decoder to get the position, as MabAudioPlayer.position method does. It would be really handy if ProcessorNodeMixin.process() method also had the AudioTime parameter along with the AudioBuffer.
> 
> Since `position` has different implications depending on the context and the processor node has responsible for processing audio data, not for calculating position, I don't think it is a good solution.

Thank you for these pointers. But will that work, for example, with FftNode? And I'm still unclear how to link the audio position with result of processing, e.g. use `FftCompletedCallback` data to create an audio spectrogram similar to this.

![image](https://github.com/SKKbySSK/coast_audio/assets/440954/19a54303-3c36-44a9-9de1-269ba231189d)

**Comment by ekuleshov** [comment]
> `FftResult` has `frames` and `format` properties. So, you can calculate the duration of the result like this... And you should sum it in each callback.

Unfortunately this approach does not work when upstream node rolled back position in the audio stream. E.g. when FftNode (only using it as an example) is hooked up in the music player and user rewinds the audio, that summed up position won't be correct anymore. I suppose I could also subscribe to that rewind event, but that is even more cumbersome.

**Comment by ekuleshov** [comment]
> ```dart
> final framesRead = graphNode.outputBus.read(buffer);
> ```

@SKKbySSK in the above snippet it only reads up to the allocated 10 sec buffer out of the `graphNode.outputBus`.
But how can I continuously read the entire decoded audio stream, say in chunks of 256 frames?
