### ISSUE TITLE
Pitch recognition

### ISSUE THREAD

**Issue by ivanesi** [SKKbySSK/coast_audio#20]
I'm going to create ear training app, and need to recognize the pitch user sing in real time. Is it possible with your package?

**Comment by ekuleshov** [comment]
> I'm going to create ear training app, and need to recognize the pitch user sing in real time. Is it possible with your package?

I've been able to make the [pitch_detector_dart](https://pub.dev/packages/pitch_detector_dart) work with the output of the `MabAudioDecoder` but not with `WavAudioDecoder`.

The former generates data in float32 and the former in int16. @SKKbySSK could you advice how to convert one to another?

**Comment by SKKbySSK** [comment]
@ekuleshov I think this is a different question than the original question, so could you please create another issue?

**Comment by SKKbySSK** [comment]
@ivanesi
This package can process microphone audio in real time, but it does not provide pitch detection.
Therefore, you will need to write your own algorithm for pitch detection on the audio data.
