### ISSUE TITLE
When I compiled the apk for Android, `NativeDecoder` was not found

### ISSUE THREAD

**Issue by Nayuta403** [SKKbySSK/coast_audio#28]
Sorry to interrupt.

Running the music_player on Android fails, indicating that `work.kscafe.coast_audio_native_codec.NativeDecoder` does not exist
![image](https://github.com/SKKbySSK/coast_audio/assets/40540394/0491be8d-c420-48f5-9181-6e3c38270b4f)
I wonder if this NativeDecoder class is generated by some instruction

**Comment by SKKbySSK** [comment]
@Nayuta403 
Oops, can you try switching to `feature/refactor` branch instead?
This branch has one example Flutter app which can play music.

**Comment by Nayuta403** [comment]
@SKKbySSK 
Thanks, this problem no longer exists, but there are no examples of fft usage in the examples. In fact, I mainly want to see the use of fft here, there are other materials can refer to

**Comment by SKKbySSK** [comment]
@Nayuta403 
FFT is not supported by this package yet.
But you can combine this package and other fft libraries to run FFT. (such as https://pub.dev/packages/fftea)

This program will run the FFT on 440 Hz sine wave
```dart
// define the audio format with 48khz sample rate and stereo channels.
final format = AudioFormat(sampleRate: 48000, channels: 1, sampleFormat: SampleFormat.int16);

// create a sine wave function node with 440hz frequency.
final functionNode = FunctionNode(
  function: const SineFunction(),
  frequency: 440,
);

AllocatedAudioFrames(length: 1024, format: format).acquireBuffer((buffer) {
  // read the audio data from the function node to the buffer.
  functionNode.outputBus.read(buffer);

  // floatList contains sine wave audio data.
  final floatList = buffer.asFloat32ListView();

  // Run FFT on the floatList here
  final fft = FFT(floatList.length);
  final freq = fft.realFft(floatList);
});
```

**Comment by Nayuta403** [comment]
@SKKbySSK Thank you very much for the information you provide. Maybe I can run it based on the refactor branch first, and refer to the content of the main branch for related use.
