### ISSUE TITLE
Error: Invalid argument(s): Failed to load dynamic library 'libcoast_audio.so': dlopen failed: library "libcoast_audio.so" not found

### ISSUE THREAD

**Issue by MaayanBogin** [SKKbySSK/coast_audio#31]
File already exists: /data/user/0/com.flutter.replicateroopflutter/app_flutter/android/src/main/jniLibs/libcoast_audio.so but this error keeps showing up

Thanks in advance :)

**Comment by SKKbySSK** [comment]
@MaayanBogin 
Hello, sorry for my late response.

It looks like you've misconfigured the Android setup.
You must place `libcoast_audio.so` file in the `{Flutter Project Dir}/android/src/main/jniLibs/{ABI}` directory.

This package support 4 ABIs: `arm64-v8a`, `armeabi-v7a`, `x86_64` and `x86`
Your directory structure should look like this:
- {Flutter Project Dir}/android/src/main/jniLibs
  - arm64-v8a
    - libcoast_audio.so
  - armeabi-v7a
    - libcoast_audio.so
  - x86_64
    - libcoast_audio.so
  - x86
    - libcoast_audio.so
