### ISSUE TITLE
Running Audio Recorder from example app on iOS: RangeError: Invalid value: Not in inclusive range 0..3: 4

### ISSUE THREAD

**Issue by hpoul** [SKKbySSK/coast_audio#32]
Hello,
I have tried running the `example/` app on iOS (iPhone Xr, iOS 17.4.1) and got the following error when selecting "Start Recording" in the `Audio Recorder`:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError: Invalid value: Not in inclusive range 0..3: 4
#0      Array._checkIndex (dart:ffi-patch/ffi_patch.dart:349:7)
#1      ArrayCharExtension.setAsciiString (package:coast_audio/src/ffi_extension.dart)
#2      WavAudioEncoder.start (package:coast_audio/src/encoder/wav/wav_audio_encoder.dart:50:23)
#3      RecorderIsolate._worker (package:example/isolates/recorder_isolate.dart:64:13)
#4      _audioIsolateRunner.runWorker (package:coast_audio/src/isolate/audio_isolate.dart:18:23)
#5      _audioIsolateRunner (package:coast_audio/src/isolate/audio_isolate.dart:50:7)
```

<details><summary>`flutter doctor`</summary>
<p>

➜  example git:(main) ✗ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.4.1 23E224 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.1)
[✓] VS Code (version 1.89.0)
[✓] Connected device (4 available)
[✓] Network resources                

• No issues found!
➜  example git:(main) ✗ 

</p>
</details> 

thanks

**Comment by SKKbySSK** [comment]
Hello @hpoul .
Sorry for my late response.

Can you try the latest `example` app on the main branch?
It may fix the problem.

**Comment by hpoul** [comment]
@SKKbySSK thanks, looks good.. although the example still throws errors when stopping the recording.. but everything seems to work.. you didn't encounter those exceptions? would it be possible to release a new version to pub?

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Messenger is not attached to an worker
#0      AudioIsolateHostMessenger.request (package:coast_audio/src/isolate/audio_isolate_messenger.dart:27:7)
#1      AudioIsolate.request (package:coast_audio/src/isolate/audio_isolate.dart:106:23)
#2      PlayerIsolate.getPosition (package:example/isolates/player_isolate.dart:133:21)
#3      _PlayerTileState.build.<anonymous closure> (package:example/components/player_tile.dart:160:50)
#4      _PlayerTimerBuilderState._init.<anonymous closure> (package:example/components/player_tile.dart:267:43)
#5      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#6      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

thanks
