### ISSUE TITLE
Can you add Linux support?

### ISSUE THREAD

**Issue by hl4hck** [SKKbySSK/coast_audio#4]
Great works!

I'm looking for a flutter package that handles audio buffers in Linux.
Can you add Linux support?

**Comment by SKKbySSK** [comment]
Thanks!

The package `coast_audio` already have Linux support which can handle audio buffers.
What are you intended to use audio buffers for?

**Comment by hl4hck** [comment]
That's great!

I'm sorry. I am newbie to Flutter. I didn't know if your package already supports Linux.
I'm trying to make sound effects that modify audio buffers in real time.  I need to port existing sound effects written in C/C++ to Flutter.

Thank you!

**Comment by hl4hck** [comment]
@SKKbySSK Hi,

I want to use coast_audio_miniaudio on Linux. Can you add linux support for coast_audio_miniaudio?
I tested mabridge build-android.sh and build-apple.sh, and they work fine.
Can you add build-linux.sh similarly?

**Comment by hl4hck** [comment]
@SKKbySSK 
I'm currently working on creating an audio effect module that can run on Tizen TV OS. After discovering that it is possible to create apps for Tizen using Flutter-Tizen, I plan to install your music_player sample app on Tizen TV OS and integrate my audio effect module to verify it. 
If coast_audio_miniaudio is compatible with Tizen, that would be fantastic.

https://github.com/flutter-tizen/plugins/issues/558

**Comment by SKKbySSK** [comment]
@hl4hck 
It seems Tizen uses its custom audio backend.(Correct me if it it wrong)
And miniaudio does not support Tizen OS.

Because of these problems, you cannot use the coast_audio_miniaudio.
Instead, you need to implement custom audio node to play raw PCM buffer.

[tizen_interop](https://github.com/flutter-tizen/tizen_interop) already wraps APIs by using ffi so maybe you can use it to implement the node(s).

**Comment by hl4hck** [comment]
@SKKbySSK 
I understand. I thought miniaudio would work, but it seems like I was wrong. I should look into tizen_interop as you suggested. Thank you for answering my questions.

**Comment by SKKbySSK** [comment]
No sweat. I hope your project going well.
