### ISSUE TITLE
FX on Audio Stream

### ISSUE THREAD

**Issue by llorenzo** [SKKbySSK/coast_audio#5]
Hi, this package seems interesting.
Low level Audio Processing is missing in Flutter.
I thought of an App that can listen to incoming audio and process effects on the stream.
Latency at 128 or 256 samples?
Is this possible?

**Comment by SKKbySSK** [comment]
In short, yes. It is technically possible.

You can use [MabCaptureDevice](https://github.com/SKKbySSK/coast_audio/blob/0205373f81bce618c2c1dd9212872740e1bac265/packages/coast_audio_miniaudio/lib/src/ma_bridge/mab_device.dart#L195) and set `bufferFrameSize` parameter to 128 or 256 frames(samples).
