### ISSUE TITLE
Is the `flutter_coast_audio_miniaudio` support ios simulator?

### ISSUE THREAD

**Issue by littleGnAl** [SKKbySSK/coast_audio#8]
Is the `flutter_coast_audio_miniaudio` support ios simulator? I got this error when building with ios simulator
```
User-Defined Issue (Xcode): Unsupported Swift architecture
/my/path/coast_audio/examples/audio_recorder/build/ios/Debug-iphonesimulator/flutter_coast_audio_miniaudio/flutter_coast_audio_miniaudio.framework/Headers/flutter_coast_audio_mini
audio-Swift.h:274:1


Parse Issue (Xcode): Could not build module 'flutter_coast_audio_miniaudio'
/my/path/coast_audio/examples/audio_recorder/ios/Runner/GeneratedPluginRegistrant.m:29:8


Could not build the application for the simulator.
Error launching application on iPhone 14 Pro.
```

**Comment by SKKbySSK** [comment]
Yes, it support simulators on Apple Silicon (Intel mac is not supported).

I've ever seen your error message on my local environment. 
Could you attach your Podfile and `GeneratedPluginRegistrant.m`?

**Comment by littleGnAl** [comment]
Thanks for your reply, I try to run the example on the x86_64 simulator, but after digging into the code, I confirm that it's not support x86_64 macos and simulator.
<img width="349" alt="image" src="https://github.com/SKKbySSK/coast_audio/assets/8847263/33e46c73-523a-4bdd-b16c-fb07b56b0f31">
